title: Neon & Noise
author: Matt Casanova
description: Game engines, terminals, and things that go fast.
url: "https://mattcasanova.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: mattcasanova

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
